# -*- coding: utf-8 -*-
"""CS102 C Fall 2021 - Intro to Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19nFLowPmNhpY7_PpBtGyFPOl-6KaVaoo

Welcome to CS 102 Section C Fall 2021 Intro Python
"""

counter = 1
name = 'cs102c'

print('{0} : counter = {1} {0}'.format(name, counter))

"""Let's do a for loop"""

words = ['cat', 'window', 'defenestrate', 'mouse']
print('Length of list is {}'.format(len(words)))
for w in words:
  print('word = {}'.format(w))
print('Done')

for i in range(len(words)):
  print(i, words[i])

"""Try if statements"""

x = True
y = False

if x is not True:
  print('x is True')
elif y is False:
  print("x is True AND y is False")
else:
  print('x is True')

"""Intro to Python Functions"""

def calculate_mean(the_list):
  print('type of the_list is {}'.format(type(the_list)))
  the_sum = sum(the_list)
  print('sum(the_list) = {}'.format(the_sum))
  the_mean = the_sum / len(the_list)
  return the_mean

my_list = [1,2,3,4,5,6,7,8,9]
my_list = [6,1,5,2,7,3,9,4,8]
my_list.sort()
print(my_list)
#print(sum(my_list)/len(my_list))
mean = calculate_mean(my_list)
print('mean = {}'.format(mean))

"""Let's create a function that calculates and returns the median of a list of integers"""

def calculate_median(the_list):
  a = the_list.copy()
  a.sort()
  list_length = len(my_list)
  middle_index = int(list_length / 2);
  #print('middle_index = {}'.format(middle_index))
  median_value = my_list[middle_index]
  return median_value

my_list = [6,1,5,2,7,3,9,4,8]
median_value = calculate_median(my_list)
print('median value of the list {} is {}'.format(my_list, median_value))